apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vontres-ai-vs
spec:
  hosts:
  - "*"
  gateways:
  - vontres-ai-gateway
  http:
  - match:
    - uri:
        prefix: /api
    route:
    - destination:
        host: vontres-ai-service
        port:
          number: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: vontres-ai-dr
spec:
  host: vontres-ai-service
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN
    connectionPool:
      tcp:
        maxConnections: 100
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutiveErrors: 5
      interval: 30s
      baseEjectionTime: 30s
      maxEjectionPercent: 10